version: '3'

networks:
  backend:
    driver: bridge

services:
  neo4j:
    image: neo4j
    build: ..
    networks:
      - backend
    environment:
      NEO4J_HOST: 0.0.0.0
      NEO4J_AUTH: none
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,cyfhir.*,gds.*
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

  express-backend:
    image: express-backend
    build: ../express
    environment:
      NEO4J_URI: 'bolt://neo4j:7687'
      NEO4J_USER: 'neo4j'
      NEO4J_PASSWORD: 'password'
    depends_on:
      - neo4j
    networks:
      - backend
    ports:
      - "3000:3000"
